### ISSUE TITLE
npm run firefox does not run Firefox

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#157]
```sh
$ git rev-parse --short HEAD # c138fbb
```

---

### Steps to reproduce:

```sh
$ npm run firefox

> tracking-protection-experiment@1.0.0 firefox /Users/pdehaan/dev/github/mozilla/blok
> npm run bundle && web-ext run


> tracking-protection-experiment@1.0.0 bundle /Users/pdehaan/dev/github/mozilla/blok
> browserify -d -t envify src/js/background.js > src/js/background.bundle.js

Running web extension from /Users/pdehaan/dev/github/mozilla/blok

run: InvalidManifest: Error parsing manifest.json at /Users/pdehaan/dev/github/mozilla/blok/manifest.json: InvalidManifest: Could not read manifest.json file at /Users/pdehaan/dev/github/mozilla/blok/manifest.json: Error: ENOENT: no such file or directory, open '/Users/pdehaan/dev/github/mozilla/blok/manifest.json'
    at /Users/pdehaan/dev/github/mozilla/blok/node_modules/web-ext/dist/webpack:/src/util/manifest.js:9:1805


npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/pdehaan/.nvm/versions/node/v6.3.0/bin/node" "/Users/pdehaan/.nvm/versions/node/v6.3.0/bin/npm" "run" "firefox"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! tracking-protection-experiment@1.0.0 firefox: `npm run bundle && web-ext run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tracking-protection-experiment@1.0.0 firefox script 'npm run bundle && web-ext run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tracking-protection-experiment package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bundle && web-ext run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tracking-protection-experiment
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tracking-protection-experiment
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/github/mozilla/blok/npm-debug.log
```

I was in the middle of trying to test #156, but I'll try and debug more later. I'm guessing I may just have to pass in the `src` directory now that this was refactorized.

**Comment by pdehaan** [comment]
I'm guessing that I'm right, because passing `-s src` hackily like `npm run firefox -- -s src` gets me a bit further (but them implodes upon itself because I think I already have a Blok Firefox session running while I was testing the last PR):

```
> tracking-protection-experiment@1.0.0 firefox /Users/pdehaan/dev/github/mozilla/blok
> npm run bundle && web-ext run "-s" "src"


> tracking-protection-experiment@1.0.0 bundle /Users/pdehaan/dev/github/mozilla/blok
> browserify -d -t envify src/js/background.js > src/js/background.bundle.js

Running web extension from /Users/pdehaan/dev/github/mozilla/blok/src
Running Firefox with profile at /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/6b38f369-9ebf-43af-a570-df02eec27a73

run: WebExtError: Cannot listen on port 6005 because it's in use
    at /Users/pdehaan/dev/github/mozilla/blok/node_modules/web-ext/dist/webpack:/src/firefox/index.js:9:4891
    at lib$es6$promise$$internal$$tryCatch (/Users/pdehaan/dev/github/mozilla/blok/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/pdehaan/dev/github/mozilla/blok/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/Users/pdehaan/dev/github/mozilla/blok/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/Users/pdehaan/dev/github/mozilla/blok/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
